apiVersion: v1
kind: Service
metadata:
  labels:
    app: flexlb-kube-controller
  name: flexlb-metrics-service
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: flexlb-kube-controller
