# permissions for end users to edit flexlbinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flexlbinstance-editor-role
rules:
- apiGroups:
  - crd.flexlb.gitee.io
  resources:
  - flexlbinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.flexlb.gitee.io
  resources:
  - flexlbinstances/status
  verbs:
  - get
