apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flexlb-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flexlb-manager-role
subjects:
- kind: ServiceAccount
  name: flexlb-kube-controller
  namespace: kube-system
