apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexlb-kube-controller
  namespace: kube-system
  labels:
    app: flexlb-kube-controller
spec:
  selector:
    matchLabels:
      app: flexlb-kube-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: flexlb-kube-controller
    spec:
      serviceAccountName: flexlb-kube-controller
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      containers:
      - name: flexlb-kube-controller
        image: flexlb-kube-controller:0.4.0
        env:
        - name: FLEXLB_TLS_CA_CERT
          value: "/certs/ca.crt"
        - name: FLEXLB_TLS_CLIENT_CERT
          value: "/certs/client.crt"
        - name: FLEXLB_TLS_CLIENT_KEY
          value: "/certs/client.key"
        - name: FLEXLB_REFRESH_INTERVAL
          value: "30"
        - name: FLEXLB_NAMESPACE
          value: "kube-system"
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: flexlb-client-certs
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: flexlb-client-certs
        secret:
          secretName: flexlb-client-certs
